dist: trusty
sudo: false
install: true

addons:
  sonarcloud:
    organization: "tamaragovorcin"
    token: 
      secure: "JZXR3MwBbEZmCkU4JQntl7/pfCpJJjFVhcirQtAm9PMAOyda1YqTBXoU9xNUoBYf5vZmpm+SlYihyD95R9/Pd8pntxFO1MsT4Om4vxfEq2IptKR9fZASL+B5So+kI+VGYd97kw9qwk/jc3phy/L5q5GVkRpIeMrqJoDOqs8mx/zWVPy3Xs68Mvu3bymakb0hDlv29ZxR0roBYo/byzXeuWJCq0QjZh6sJCh5tdMIZeLhxMgVLB3cvOjDrf6oYBK3xH0nGppgK1cUzelNroK83/ytG3jwXkuTVyX8O6mJasFlOqO/OSCG7BnKczvLUwDDWwrstEJHRkBSDDsNMgvsI5BvpY3VJA+mXTEnU5wPXTw6TR0y+qb3vtwC1jkwGhQih8w8VtQQ4OveJs6/LiJqWtNvWttrpZIQRYQhDq2omd2EnjHKQgyBtSqesnj8Ry03rpvz232rh3msfIALZUkc7of88S9t1ZhUKiVnNnCiH9HAeRnYAfdbeJNKEBrlKkTGkGlGGmL1v99mxTgxBdZBmCfOnjpN+rxoxky2gFM7wqyJRNWSUTUoEl5IKfJwVIONDvdtxWc41VNmaDbgKuqoWJLrL1Ct84V2O4EJbmYSNo7DuG+Z3RE6jAtjmxkU3ekJ9pkdolp90BtTQkpxQSfG9DISNYmrSopgnbhrMV+jDIk="

branches:
  only: develop

matrix:
  include:
    - language: java
      jdk:
      - oraclejdk11
      before_script:
        - cd ./Backend/
      script:
        - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=tamaragovorcin_ISA_project
      cache:
      directories:
        - '$HOME/.m2/repository'
        - '$HOME/.sonar/cache'
        
    - language: node_js
      node_js: 
        - "8.6.0"
      install:
        - npm install
      before_install:
        - cd ./Frontend/
      script:
        - npm run build
        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -F 11 -L GPL
      after-success:
        - sonar-scanner -Dsonar.projectKey=tamaragovorcin_ISA_project