spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver #
    url: ${JDBC_DATABASE_URL} # jdbc:postgresql://localhost:5432/postgres 
    username: ${JDBC_DATABASE_USERNAME} #postgres
    password: ${JDBC_DATABASE_PASSWORD} #root
    initialization-mode: always
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none #create-drop # When you launch the apzsqlplication for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    
server:
    port: 8082