DROP TABLE IF EXISTS hospitals;
CREATE TABLE hospitals(api_key VARCHAR(255) PRIMARY KEY, "name" VARCHAR(255));

DROP TABLE IF EXISTS pharmacies;
CREATE TABLE pharmacies(api_key VARCHAR(255) PRIMARY KEY, "name" VARCHAR(255), town VARCHAR(255));
